// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueF7GMOt6uH9YsslZEAeALKiI4HrOAJM',
    appId: '1:52522995198:web:33febc001ea920b0e344af',
    messagingSenderId: '52522995198',
    projectId: 'password-manager-6633e',
    authDomain: 'password-manager-6633e.firebaseapp.com',
    storageBucket: 'password-manager-6633e.appspot.com',
    measurementId: 'G-WRC3RX67L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKo-A2euCmkxO7bAsEnTgF7Ol9M_ANaYE',
    appId: '1:52522995198:android:6a66ec72186cc609e344af',
    messagingSenderId: '52522995198',
    projectId: 'password-manager-6633e',
    storageBucket: 'password-manager-6633e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8rmtDKGcekRFjwcVD2_LxWPNEOW8Mak',
    appId: '1:52522995198:ios:124373b171be0d5fe344af',
    messagingSenderId: '52522995198',
    projectId: 'password-manager-6633e',
    storageBucket: 'password-manager-6633e.appspot.com',
    androidClientId: '52522995198-21oj8f9ehsvuu9dh1vi39k6f9gsblr6j.apps.googleusercontent.com',
    iosClientId: '52522995198-d26kcl4amdvmbqs10digo43g54mnfik6.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8rmtDKGcekRFjwcVD2_LxWPNEOW8Mak',
    appId: '1:52522995198:ios:fe0f5db687bb0103e344af',
    messagingSenderId: '52522995198',
    projectId: 'password-manager-6633e',
    storageBucket: 'password-manager-6633e.appspot.com',
    androidClientId: '52522995198-21oj8f9ehsvuu9dh1vi39k6f9gsblr6j.apps.googleusercontent.com',
    iosClientId: '52522995198-2eacbd34ho10tounkfh664q0eolfp0u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager.RunnerTests',
  );
}
